export const queryKeys = {
  // Existing keys
  TENANT_SETTINGS: "tenant-settings",
  SESSION: "session",
  SELECTABLE_SESSION: "selectable-session",
  TERM: "term",
  SELECTABLE_TERM: "selectable-term",
  CLASSES: "classes",
  CLASS_ARMS: "class-arms",
  SUBJECTS: "subjects",
  SELECTABLE_SUBJECTS: "selectable-subjects",
  STUDENTS: "students",
  TENANTS: "tenants",
  PLANS: "plans",
  SUBSCRIPTION: "subscription",
  SUBSCRIPTION_PLANS: "subscription-plans",
  BILLING_HISTORY: "billing-history",
  STAFF: "staff",
  ROLES: "roles",
  // New keys for Sprint 1+
  GRADING_SYSTEMS: "grading-systems",
  CA_CONFIGS: "ca-configs",
  ASSESSMENTS_CA: "assessments-ca",
  ASSESSMENTS_EXAM: "assessments-exam",
  EXAMINATIONS: "examinations",
  TIMETABLE: "timetable",
  ATTENDANCE: "attendance",
  ATTENDANCE_SUMMARY: "attendance-summary",
  RESULTS: "results",
  DISCIPLINE: "discipline",
  ADMISSIONS: "admissions",
  INVOICES: "invoices",
  PAYMENTS: "payments",
  LEDGER: "ledger",
  FEE_STRUCTURES: "fee-structures",
  MESSAGES: "messages",
  NOTIFICATIONS: "notifications",
  REPORTS: "reports",
  AUDIT_LOGS: "audit-logs",
  SUPER_ADMIN_STATS: "super-admin-stats",
  SUPER_ADMIN_CONFIG: "super-admin-config",
  ASSIGNMENTS: "assignments",
  MY_CHILDREN: "my-children",
} as const;
